name: fipola_app
description: E-Commerce based application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  marquee: ^1.6.0
  fluttertoast: ^7.1.0
  woocommerce_api: ^0.0.9
  shared_preferences: ^0.5.12
  flutter_html: ^1.0.0
  razorpay_flutter: ^1.2.2
  flutter_progress_dialog: ^0.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/background.jpg
     - assets/logo.png
     - assets/inverted_logo.png
     - assets/facebook_logo.png
     - assets/google_logo.png
     - assets/nonveg1.jpg
     - assets/user.png
     - assets/email.png
     - assets/password.png
     - assets/phone.png
     - assets/open_now.jpg
     - assets/poster.jpg
     - assets/bbq.png
     - assets/chicken.png
     - assets/cold_cuts.png
     - assets/coupons.png
     - assets/egg.png
     - assets/exotic.png
     - assets/lamb_goat.png
     - assets/marinades.png
     - assets/pets_foods.png
     - assets/profile_pic.png
     - assets/ready_to_cook.png
     - assets/relishes.png
     - assets/sea_food.png
     - assets/lollipop.jpg
     - assets/pepper_chicken.jpeg
     - assets/prawns.jpg
     - assets/stay.jpg
     - assets/chicken_curry.png
     - assets/chemical.png
     - assets/motorcycle.png
     - assets/no-drugs.png
     - assets/green-antibiotic.png
     - assets/chicken_biriyani.png
     - assets/chicken_breast.png
     - assets/chicken_cube.png
     - assets/chicken_curry_skinless.png
     - assets/chicken_leg.png
     - assets/whole_chicken.jpg
     - assets/order.png
     - assets/shopping-bag.png
     - assets/product.png
     - assets/poster2.jpg
     - assets/logo.jpeg
     - assets/poster3.jpg
     - assets/tick.png
     - assets/location.png
     - assets/nonban1.jpg
     - assets/nonban2.png
     - assets/nonban3.png
     - assets/nonban4.jpg
     - assets/nonban5.jpg
     - assets/instagram.png
     - assets/twitter.png
     - assets/visa.png
     - assets/payu.png
     - assets/maestro.png
     - assets/food_delivery.png
     - assets/preservatives.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


